# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A accuracy computation function
#' @description A accuracy computation function using Rcpp
#' @param N the number of samples
#' @param a matrix a
#' @param b matrix b
#' @return the accuracy ratio
#' @import Rcpp
#' @examples
#' \dontrun{
#' acc(3,as.matrix(c(1,2,3)),as.matrix(c(2,3,4)))
#' }
#' @export
acc <- function(N, a, b) {
    .Call('_StatComp22080_acc', PACKAGE = 'StatComp22080', N, a, b)
}

